ifeq ($(CONFIG_OPLUS_FAN_MTK),y)
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/pwm/pwm_v2/include/
endif

obj-$(CONFIG_OPLUS_FAN)	+= oplus_fan.o
