#for AWINIC AW87XXX Smart K PA
snd-soc-aw87xxx-objs := aw87xxx.o aw87xxx_device.o aw87xxx_monitor.o aw87xxx_bin_parse.o aw87xxx_dsp.o aw87xxx_acf_bin.o
obj-$(CONFIG_SND_SOC_AW87XXX) += snd-soc-aw87xxx.o