ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/input/touchscreen/chsc5448_p785/

obj-m += chsc5448_p785.o
chsc5448_p785-y += basic_util.o
chsc5448_p785-y += i2c_communication.o
chsc5448_p785-y += mtk_core.o
chsc5448_p785-y += semi_touch_function.o
chsc5448_p785-y += semi_touch_upgrade.o
chsc5448_p785-y += semi_touch_apk.o
chsc5448_p785-y += semi_touch_device.o
chsc5448_p785-y += semi_touch_custom.o
chsc5448_p785-y += mtk_tpd.o
chsc5448_p785-y += tpd_button.o
chsc5448_p785-y += tpd_debug.o
chsc5448_p785-y += tpd_default.o
chsc5448_p785-y += tpd_misc.o
chsc5448_p785-y += tpd_setting.o


